#!/bin/bash

while getopts "n:t:" opt; do
  case $opt in
  n) name="$OPTARG" ;;
  t) time="$OPTARG" ;;
  *)
    echo "Invalid option"
    exit 1
    ;;
  esac
done

# Prompt for missing inputs if needed
if [ -z "$name" ]; then
  read -p "Enter name: " name
fi

if [ -z "$time" ]; then
  read -p "Enter time: " time
fi

# Notify start
spd-say "Starting timer for $name, lasting $time"

# Run commands
clear
timer --format 24h -n "$name" $time && {
  spd-say "$name, is finished!"
  notify-send -u critical -a "Timer Script" -t 5000 -i dialog-information "$name" "Timer is finished!"
}
