#!/bin/bash

usage() {
  echo "Usage: $0 [--dry] -m R|L -h <hostname> <local_port> [-t <target_port>]"
  exit 1
}

DRY_RUN=false
MODE=""
HOST=""
TARGET_PORT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
  --dry)
    DRY_RUN=true
    shift
    ;;
  -m)
    MODE="$2"
    shift 2
    ;;
  -h)
    HOST="$2"
    shift 2
    ;;
  -t)
    TARGET_PORT="$2"
    shift 2
    ;;
  *)
    if [[ -z "$LOCAL_PORT" ]]; then
      LOCAL_PORT="$1"
      shift
    else
      usage
    fi
    ;;
  esac
done

if [[ -z "$MODE" || -z "$HOST" || -z "$LOCAL_PORT" ]]; then
  usage
fi

if [[ "$MODE" != "R" && "$MODE" != "L" ]]; then
  usage
fi

MODE="-$MODE"
TARGET_PORT=${TARGET_PORT:-$LOCAL_PORT}

COMMAND="ssh $MODE $LOCAL_PORT:localhost:$TARGET_PORT $HOST"

if $DRY_RUN; then
  echo "$COMMAND"
else
  eval "$COMMAND"
fi
